version: "2.1"

services:
  app:
    image: maven:3-jdk-8-alpine
    ports:
      - 8080:8080
    volumes:
      - ./:/app:delegated
      - ~/.m2:/root/.m2:delegated
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: "/app"
    command: ["sh", "redeploy.sh"]
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432
    healthcheck:
      # Command to run inside the container to check its health status
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
